

var payload = { paymentTransactionId: '10000011523706193178',
paymentMode: 'Cash',
_id: 'OR201804144',
name: 'StoreKing12',
logistics: 10,
orderAmount: 436,
paymentStatus: 'Paid',
type: 'Physical',
fulfilledBy: 'MPS0',
orderType: 'Wholesale',
isExclusiveType: false,
transactionId: '10000121523706192905',
remarks: 'Checkout for cart vm.cartId',
__v: 0,
exclusivetype: [],
releaseOnHoldAmount: false,
logs: [],
needOrderIdCorrection: false,
partnerOrderDetails: { otherCharges: 0, shippingCharges: 0 },
mpsShipped: false,
commissionUpdated: false,
descriptiveCommission: 
 { imeiCommission: { amount: 0, paid: false },
   physicalCommission: { amount: 0, paid: false },
   skCommission: { amount: 0, paid: false },
   logistics: { amount: 0, paid: false } },
skApp: true,
payoutHappened: false,
batchEnabled: true,
returns: [],
deleted: false,
subOrdersCreated: true,
deals: 
 [ { quantity: 1,
     id: 'D4548602820',
     _id: "5ad1e940934b9f7daf1d0d95",
     price: 426 } ],
invoices: [],
billingAddress: 
 { pincode: 560074,
   state: 'Karnataka',
   district: 'Bangalore',
   city: 'Kengeri',
   landmark: 'doddahaladamara' },
shippingAddress: 
 { landmark: 'doddahaladamara',
   city: 'Kengeri',
   district: 'Bangalore',
   state: 'Karnataka',
   pincode: 560074 },
franchise: 
 { state: 'Karnataka',
   name: 'Testing StoreKing RMF',
   district: 'Bangalore',
   city: 'Kengeri',
   pincode: '560074',
   town: 'Kengeri',
   accountId: '10000000003',
   type: 'RMF',
   parent: 'F100001',
   id: 'F100001',
   mobile: '9743537525',
   code: '37533523',
   address: 
    { landmark: 'doddahaladamara',
      full_address: 'kumbalagudu 2nd phase,gerupalya',
      street: 'near prajavani press',
      door_no: 'Local cube pvt Ltd' } },
readyForBatching: false,
stockAllocation: 'NotAllocated',
subOrders: 
 [ { id: 'D4548602820',
     name: 'Lakme Nail polish Pink',
     shipsIn: '24-48 Hrs',
     mrp: 500,
     memberPrice: 0,
     b2bPrice: 426,
     orgPrice: 426,
     invoice_seperately: false,
     quantity: 1,
     price: 426,
     kingsale: '',
     _id: 'OR201804144_1',
     logs: [Object],
     batchId: '',
     invoiced: false,
     readyToShip: false,
     inwardScan: false,
     processed: false,
     readyForBatching: false,
     gotRequestedProducts: false,
     snapshots: [],
     blockedProducts: [],
     requestedProducts: [],
     internalStatus: 'Confirmed',
     commission: [Object],
     status: 'Pending',
     kingsaleDisc: 0,
     couponDisc: 0,
     products: [Object],
     claimed: 0,
     brand: [Object],
     category: [Object],
     shippingCharges: 0,
     images: [],
     encryptedShipmentId: '0',
     cashOnDeliveryCharge: 0 } ],
gotRequestedProducts: false,
disabledBatch: false,
commissionReleasedAt: 'Shipped',
source: 'WMF0',
invoiced: false,
readyToShip: false,
processed: false,
inwardScan: false,
discount: 0,
notification: 
 { Delivered: true,
   'Partially Delivered': true,
   Closed: true,
   Shipped: true,
   'Partially Shipped': true,
   Processing: true,
   Cancelled: true,
   Invoiced: true,
   Confirmed: true,
   'Payment Initiated': true,
   Created: false },
status: 'Confirmed',
kingsale: [],
kingsaleDisc: 0,
couponDisc: 0,
coupon: 
 { discount: 0,
   couponDiscPerDeal: [],
   isCouponUsed: false,
   isCouponUpdated: false },
useWallet: true,
vatFixed: false,
autoConfirm: true,
autoCancel: true,
isOffline: false,
typeOfOrder: 'SK' }




    console.log("--json--" , JSON.stringify(payload));