var cities = {
    '246': 'Bangalore',
    '567': 'Chennai',
    "789": 'Hyderabad',
    "8576": 'Hyderabad',
    "3845": 'Hyderabad',
    "38438": 'Hyderabad',
    "546": 'Hyderabad',
    "456": 'Hyderabad',
    "346": 'Hyderabad',
    "sdfg": 'Hyderabad',
    "hghf": 'Hyderabad',
    "xcvzv": 'Hyderabad',
    "fdgfd": 'Hyderabad',
    "gjghj": 'Hyderabad',
    "cvxc": 'Hyderabad',
    "e656": 'Hyderabad',
    "gfdhth": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
    "789": 'Hyderabad',
};

function returnCities() {
    return cities;
}